version: "3"
services:
  home-root:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx-do.conf:/etc/nginx/conf.d/nginx.conf
      - ${DATA_DIR}/home-root:/usr/share/nginx/html
      - ${PWD}/cert/archive:/etc/ssl
      - ${DATA_DIR}:/www
    restart: always
  carltonathome:
    image: php:7.2.1-apache
    ports:
      - "8103:80"
    volumes:
      - ${DATA_DIR}/carltonathome:/var/www/html
    domainname: carltonathome.com
    restart: always
  appsfortracking:
    image: "node"
    ports:
      - "8101:5000"
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      - ${DATA_DIR}/apps4tracking/api:/home/node/app
    command: "npm start"
    restart: always
  sophieandchampagne:
    image: node
    ports:
      - "8107:80"
    volumes:
      - ${DATA_DIR}/sophieandchampagne/api:/home/node/app
    restart: always
