version: "3"
services:
  home-root:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx-home.conf:/etc/nginx/conf.d/nginx.conf
      - ${DATA_DIR}/home-root/web:/usr/share/nginx/html
      - ${DATA_DIR}:/www
  carltonathome:
    image: php:7.2.1-apache
    ports:
      - "8103:80"
    volumes:
      - ${DATA_DIR}/carltonathome/web:/var/www/html
    domainname: carltonathome.com
  appsfortracking:
    image: "node"
    ports:
      - "8101:5000"
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      - ${DATA_DIR}/apps4tracking/api:/home/node/app
    command: "npm start"
  sophieandchampagne:
    image: node
    ports:
      - "8107:80"
    volumes:
      - ${DATA_DIR}/sophieandchampagne/api:/home/node/app
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    command: "npm start"
