version: "3"
services:
  home-root:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx-do.conf:/etc/nginx/conf.d/nginx.conf
      - ${DATA_DIR}/home-root:/usr/share/nginx/html
      - ${PWD}/cert/archive:/etc/ssl
    restart: always
  carltonathome:
    image: php:7.2.1-apache
    ports:
      - "8103:80"
    volumes:
      - ${DATA_DIR}/carltonathome:/var/www/html
    domainname: carltonathome.com
    restart: always
  carltonwin8:
    image: nginx
    ports:
      - "8105:80"
    volumes:
      - ${DATA_DIR}/carltonwin8:/usr/share/nginx/html
    restart: always
  tinaandcarlton:
    image: nginx
    ports:
      - "8106:80"
    volumes:
      - ${DATA_DIR}/tinaandcarlton:/usr/share/nginx/html
    restart: always
  appsfortracking:
    image: "node:10.15.0"
    ports:
      - "8101:5000"
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      - ${DATA_DIR}/apps4tracking:/home/node/app
    command: "npm start"
    restart: always
