version: "3"
services:
  home-root:
    build:
      context: .
      dockerfile: ./Dockerfile.home
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ${DATA_DIR}/home-root:/usr/share/nginx/html
  apps4tracking:
    image: "node:10.14.2"
    ports:
      - "8101:5000"
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      - ${DATA_DIR}/apps4tracking:/home/node/app
      # need to figure out why the command below does not work by running it locally
      #    command: "sh -c 'cd server && npm install && cd .. && npm run server'"
  carltonathome:
    image: php:7.2.1-apache
    ports:
      - "8103:80"
    volumes:
      - ${DATA_DIR}/carltonathome:/var/www/html
  carltonjoseph:
    image: nginx
    ports:
      - "8104:80"
    volumes:
      - ${DATA_DIR}/carltonjoseph:/usr/share/nginx/html
  carltonwin8:
    image: nginx
    ports:
      - "8105:80"
    volumes:
      - ${DATA_DIR}/carltonwin8:/usr/share/nginx/html
  tinaandcarlton:
    image: nginx
    ports:
      - "8106:80"
    volumes:
      - ${DATA_DIR}/tinaandcarlton:/usr/share/nginx/html
